### ISSUE TITLE
Better structure for project

### ISSUE THREAD

**Issue by rpunkfu** [zzarcon/gh-emoji#16]
We should probably move files to lib, bin directories and in future separate it into some modules, same goes for the tests. What do you think @zzarcon?

**Comment by ryyppy** [comment]
What would you put into the `bin` directory? Because usually this is a pretty common directory for global node scripts in npm packages

**Comment by rpunkfu** [comment]
Usually `bin` is an entry point for npm and all functionality is imported from `lib`. It was just a loose idea, I'd love to know your opinion @ryyppy :)

**Comment by ryyppy** [comment]
So usually for ES6 people tend to use the `./src` directory... I would also suggest to split functionality of `gh-emoji.js` up in multiple files as the code grows, so we maybe wanna move the current source to `src/index.js` and iterate from there

**Comment by rpunkfu** [comment]
Yes, that's what I proposed yesterday to @zzarcon :)

**Comment by rpunkfu** [comment]
Will open PR with it later :)

**Comment by rpunkfu** [comment]
Structure is pretty much improved with #23 & #25. There's going to be a new issue about splitting functionality into multiple modules.
