### ISSUE TITLE
Auto-Generate API docs

### ISSUE THREAD

**Issue by ryyppy** [zzarcon/gh-emoji#21]
I was always thinking about automating API documentation, because docs will eventually get out of sync with the actual implementation after a while...

I don't like `jsdoc` because it is bad for ES6 modules, but maybe it would be interesting to add http://documentation.js.org/ support, since this tool can also render to Markdown ... I also saw somewhere that it can parse `flowtype` declarations.

**Comment by rpunkfu** [comment]
I love this idea! :)

**Comment by oskarcieslik** [comment]
Testing slack integration

**Comment by zzarcon** [comment]
I love `documentation.js` <3

**Comment by rpunkfu** [comment]
Closed with #22
