### ISSUE TITLE
Demo is not working on Safari or mobile-Safari

### ISSUE THREAD

**Issue by MP0w** [zzarcon/gh-emoji#28]
...

**Comment by joanromano** [comment]
Wondering why

**Comment by ryyppy** [comment]
Hmm, maybe a cross-domain XHR problem? Hard to test without any environment information... would be helpful if you could provide us with platform specs and in the best case, also with some browser debug information!

**Comment by zzarcon** [comment]
I'm pretty sure is related to https://github.com/wheresrhys/fetch-mock. Which actually we are not using in the demo at all....

**Comment by zzarcon** [comment]
@MP0w @joanromano @ryyppy fixed in https://github.com/zzarcon/gh-emoji/pull/29 please take a look in Safari again
