### ISSUE TITLE
Add FlowType support

### ISSUE THREAD

**Issue by ryyppy** [zzarcon/gh-emoji#5]
Hi! Are there any plans to add FlowType declarations for this lib? :trollface:

**Comment by zzarcon** [comment]
Hi @ryyppy! it wasn't on the roadmap but, now that you said I'll actually love to add FlowType support. Can you help me with that or send me any good article that explains how to add it? :trolleybus:

**Comment by zzarcon** [comment]
Done in https://github.com/zzarcon/gh-emoji/pull/14
