### ISSUE TITLE
Build process should also create minified version of gh-emoji

### ISSUE THREAD

**Issue by rpunkfu** [zzarcon/gh-emoji#7]
What do you think @zzarcon?

**Comment by zzarcon** [comment]
Totally agree on that

**Comment by rpunkfu** [comment]
Cool! Will work on that after autocomplete in demo is done :)

**Comment by zzarcon** [comment]
Great! Let me know if you are not sure about how to do it

**Comment by rpunkfu** [comment]
Closed with #9
